# Generated by Django 4.1.7 on 2023-04-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=56)),
                ('description', models.CharField(max_length=2000)),
                ('image1', models.ImageField(default='abc.jpg', upload_to='images')),
                ('image2', models.ImageField(default='abc.jpg', upload_to='images')),
                ('image3', models.ImageField(default='abc.jpg', upload_to='images')),
                ('quantity', models.IntegerField(default=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
